config/routes.rb
Blogit::Engine.routes.draw do

  # Keep these above the posts resources block
  get "posts/page/:page" => "posts#index"
  get "posts/tagged/:tag" => 'posts#tagged', as: :tagged_blog_posts

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  get "/" => "posts#index", as: :blog_root
end

app/models/blogit/comment.rb
module Blogit
  class Comment < ActiveRecord::Base
    
    # require custom validators
    require "validators"
    include Validators
    
    # ================
    # = Associations =
    # ================
    
    belongs_to :post, class_name: "Blogit::Post", 
      foreign_key: "post_id", counter_cache: true, touch: true
    
    # TODO: Check if this is optimal
    URL_REGEX   = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?\Z/ix

    # TODO: Check if this is optimal    
    EMAIL_REGEX = /\A[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\Z/i
    
    # ============
    # = Callbacks =
    # ============
    
    before_validation :format_website
    
    # ==============
    # = Attributes =
    # ==============
    
    # nickname acts as a "honeypot" to catch spam
    # the form field should be hidden using CSS and so 
    # if present, must be spam.
    # 
    # @attribute
    attr_accessor :nickname
    
    
    # ===============
    # = Validations =
    # ===============

    # nickname acts as a "honeypot" to catch spam
    # the form field should be hidden using CSS and so 
    # if present, must be spam.
    validates :nickname, absence: true
    validates :name, presence: true
    validates :email, presence: true, format: {with: EMAIL_REGEX, allow_blank: true }
    validates :body, presence: true, length: { minimum: 4, allow_blank: true}
    validates :website, format: {with: URL_REGEX, allow_blank: true}
        
  private
    
    # Prepend http to the url before the validation check
    def format_website
      if self.website.present? and self.website !~ /^http/i
        self.website = "http://#{self.website}"
      end
    end
    
  end
end

app/models/blogit/post.rb
module Blogit
  class Post < ActiveRecord::Base

    require "acts-as-taggable-on"
    require "kaminari"

    include ::ActionView::Helpers::TextHelper

    acts_as_taggable

    self.paginates_per Blogit.configuration.posts_per_page

    # ==============
    # = Attributes =
    # ==============


    # ===============
    # = Validations =
    # ===============

    validates :title, presence: true, length: { minimum: 10, maximum: 66 }
    validates :body,  presence: true, length: { minimum: 10 }
    validates :blogger_id, presence: true

    # =================
    # = Assosciations =
    # =================

    belongs_to :blogger, :polymorphic => true

    has_many :comments, :class_name => "Blogit::Comment"

    # ==========
    # = Scopes =
    # ==========

    # Returns the blog posts paginated for the index page
    # @scope class
    scope :for_index, lambda { |page_no = 1| order("created_at DESC").page(page_no) }

    # ====================
    # = Instance Methods =
    # ====================

    def to_param
      "#{id}-#{title.parameterize}"
    end
    
    def short_body
      truncate(body, length: 400, separator: "\n")
    end
    
    def comments
      check_comments_config
      super()
    end
    
    def comments=(value)
      check_comments_config
      super(value)
    end
    

    # If there's a current blogger and the display name method is set, returns the blogger's display name
    # Otherwise, returns an empty string
    def blogger_display_name
      if self.blogger and !self.blogger.respond_to?(Blogit.configuration.blogger_display_name_method)
        raise ConfigurationError,
        "#{self.blogger.class}##{Blogit.configuration.blogger_display_name_method} is not defined"
      elsif self.blogger.nil?
        ""
      else
        self.blogger.send Blogit.configuration.blogger_display_name_method
      end
    end

    private

    def check_comments_config
      raise RuntimeError.new("Posts only allow active record comments (check blogit configuration)") unless Blogit.configuration.include_comments == :active_record
    end
    
  end
end

app/controllers/blogit/application_controller.rb
module Blogit

  # Inherits from the application's controller instead of ActionController::Base
  class ApplicationController < ::ApplicationController

    helper Blogit::ApplicationHelper, Blogit::PostsHelper
    helper_method :current_blogger, :blogit_conf

    # Sets a class method to specify a before-filter calling
    # whatever Blogit.configuration.authentication_method is set to
    # Accepts the usual before_filter optionss
    def self.blogit_authenticate(options ={})
      before_filter blogit_conf.authentication_method, options
    end

    # A helper method to access the Blogit::configuration
    # at the class level
    def self.blogit_conf
      Blogit::configuration
    end

    # A helper method to access the Blogit::configuration
    # at the controller instance level
    def blogit_conf
      self.class.blogit_conf
    end

    # Returns the currently logged in blogger by calling
    # whatever Blogit.current_blogger_method is set to
    def current_blogger
      send blogit_conf.current_blogger_method
    end

    # Returns true if the current_blogger is the owner of the post
    # @param post An instance of Blogit::Post
    def this_blogger?(post)
      current_blogger == post.blogger
    end

  end
end

app/controllers/blogit/comments_controller.rb
module Blogit
  class CommentsController < ApplicationController

    blogit_authenticate except: [:create]

    def create
      @comment = post.comments.new(comment_parameters)
      respond_to do |format|
        format.js {
          # the rest is dealt with in the view
          @comment.save
        }

        format.html {
          if @comment.save
            redirect_to(post, notice: t(:successfully_added_comment, scope: 'blogit.comments'))
          else
            render "blogit/posts/show"
          end
        }

      end

    end

    def destroy
      @comment = post.comments.find(params[:id])
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to(post, notice: t(:successfully_removed_comment, scope: 'blogit.comments'))}
        format.js
      end
    end

    private

    def post
      @post ||= Blogit::Post.find(params[:post_id])
    end
    
    def comment_parameters
      params.require(:comment).permit(:name, :email, :body, :website)
    end
    
  end
end

app/controllers/blogit/posts_controller.rb
module Blogit

  # Using explicit ::Blogit::ApplicationController fixes NoMethodError 'blogit_authenticate' in
  # the main_app
  class PostsController < ::Blogit::ApplicationController
    
    # If a layout is specified, use that. Otherwise, fall back to the default
    layout Blogit.configuration.layout if Blogit.configuration.layout
    
    # If using Blogit's Create, Update and Destroy actions AND ping_search_engines is
    # set, call ping_search_engines after these requests
    if Blogit.configuration.include_admin_actions
      after_filter :ping_search_engines, only: [:create, :update, :destroy], :if => lambda { Blogit.configuration.ping_search_engines }
    end
    
    # Raise a 404 error if the admin actions aren't to be included
    # We can't use blogit_conf here because it sometimes raises NoMethodError in main app's routes
    unless Blogit.configuration.include_admin_actions
      before_filter :raise_404, except: [:index, :show, :tagged]
    end

    blogit_authenticate(except: [:index, :show, :tagged])

    def index
      respond_to do |format|
        format.xml {
          @posts = Post.order('created_at DESC')
        }
        format.html {
          @posts = Post.for_index(params[Kaminari.config.param_name])
        }
        format.rss {
          @posts = Post.order('created_at DESC')
        }
      end
    end

    def show
      @post = Post.find(params[:id])
    end

    def tagged
      @posts = Post.for_index(params[Kaminari.config.param_name]).tagged_with(params[:tag])
      render :index
    end

    def new
      @post = current_blogger.blog_posts.new(post_paramters)
    end

    def edit
      @post = current_blogger.blog_posts.find(params[:id])
    end

    def create
      @post = current_blogger.blog_posts.new(post_paramters)
      if @post.save
        redirect_to @post, notice: t(:blog_post_was_successfully_created, scope: 'blogit.posts')
      else
        render action: "new"
      end
    end

    def update
      @post = current_blogger.blog_posts.find(params[:id])
      if @post.update_attributes(post_paramters)
        redirect_to @post, notice: t(:blog_post_was_successfully_updated, scope: 'blogit.posts')
      else
        render action: "edit"
      end
    end

    def destroy
      @post = current_blogger.blog_posts.find(params[:id])
      @post.destroy
      redirect_to posts_url, notice: t(:blog_post_was_successfully_destroyed, scope: 'blogit.posts')
    end
    
    def post_paramters
      if params[:post]
        params.require(:post).permit(:title, :body, :tag_list)
      else
        {}
      end
    end

    private

    def raise_404
      # Don't include admin actions if include_admin_actions is false
      render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
    end
    
    
    # @See the Pingr gem for more info https://github.com/KatanaCode/pingr
    def ping_search_engines
      case blogit_conf.ping_search_engines
      when Array
        search_engines = blogit_conf.ping_search_engines
      when true
        search_engines = Pingr::SUPPORTED_SEARCH_ENGINES
      end
      for search_engine in search_engines
        Pingr::Request.new(search_engine, posts_url(format: :xml)).ping
      end
    end

  end

end

app/helpers/blogit/application_helper.rb
module Blogit
  module ApplicationHelper

    TIMETAG_FORMAT = "%Y-%m-%dT%TZ"

    # Creates a div tag with class 'blog_' + (post|comment) + '_' + name
    # Eg:
    #   blog_tag(:title, "") # => <div class="blog_post_title"></div>
    #   blog_tag(:email, "", {:type => "comment"}) # => <div class="blog_comment_email"></div>
    #   blog_tag(:tweet, "", {:type => "status"}) # => <div class="blog_status_tweet"></div>
    def blog_tag(name, content_or_options = {}, options = {}, &block)
      tag_type = options.delete(:type) || "post"

      if block_given?
        content = capture(&block)
        options = content_or_options
      else
        content = content_or_options
      end
      options[:class] = "#{options[:class]} blog_#{tag_type}_#{name}".strip
      content_tag(name, content, options)
    end

    # Format content using the {Blogit::Configuration#default_parser_class default_parser_class}
    def format_content(content = nil, &block)
      content = capture(&block) if block_given?
      parser = Blogit::configuration.default_parser_class.new(content)
      parser.parsed.html_safe
    end

    # Returns the first error message for an ActiveRecord model instance
    # @param object A model instance to check
    # @param attribute A symbol or string for attribute name to check for
    #   errors
    def errors_on(object, attribute)
      error_message = object.errors[attribute].first
      content_tag(:span, error_message, class: "blogit_error_message") if error_message
    end

    # A helper method for creating a +<div>+ tag with class 'field'
    # Used for separating form fields
    def field(content_or_options={}, options ={}, &block)
      div_with_default_class(:field, content_or_options, options, &block)
    end

    # A helper method for creating a +<div>+ tag with class 'actions'
    # Used for option links and form buttons
    def actions(content_or_options={}, options ={}, &block)
      div_with_default_class(:actions, content_or_options, options, &block)
    end

    # A helper method for creating a +<div>+ tag with class 'login_required'
    # Will only render content if there is a logged in user
    def login_required(content_or_options={}, options ={}, &block)
      if current_blogger and blogit_conf.include_admin_links
        div_with_default_class(:login_required, content_or_options, options, &block)
      end
    end

    # Can search for named routes directly in the main app, omitting
    # the "main_app." prefix
    def method_missing method, *args, &block
      if main_app_url_helper?(method)
        main_app.send(method, *args)
      else
        super
      end
    end
    
    def respond_to?(method)
      main_app_url_helper?(method) or super
    end

    private

    def main_app_url_helper?(method)
      Blogit::configuration.inline_main_app_named_routes and
        (method.to_s.end_with?('_path') or method.to_s.end_with?('_url')) and
        main_app.respond_to?(method)
    end

    def div_with_default_class(default_class, content_or_options={}, options={}, &block)
      if block_given?
        content = capture(&block)
        options = content_or_options
      else
        content = content_or_options
      end
      options[:class] = "#{default_class} #{options[:class]}".strip
      content_tag(:div, content, options)
    end

  end
end

app/helpers/blogit/posts_helper.rb
module Blogit
  module PostsHelper

    # A comments tag corresponding to the comments configuration
    def comments_for(post)
      render(partial: "blogit/posts/#{Blogit.configuration.include_comments}_comments", locals: { post: post, comment: Blogit::Comment.new })
    end

    # A share bar as configured
    def share_bar_for(post)
      return "" unless Blogit.configuration.include_share_bar
      render(partial: "blogit/posts/share_bar", locals: { post: post})
    end

    # Creates a ul tag tree with posts by year and monthes. Include
    # blogit/archive.js to enabled expand collapse.
    # @param year_css [String, Symbol] The CSS class of the year UL tag
    # @param month_css [String, Symbol] The CSS class of the month UL tag
    # @param post_css [String, Symbol] The CSS class of the year LI tag
    # @param archive_posts [ActiveRecord::Relation, Array] The posts to be included in the archive (defaults to Post.all)
    # @yield[post] block responsible for writing the link (or whatever) to the post
    def blog_posts_archive_tag(year_css, month_css, post_css, archive_posts = Post.order("created_at DESC"))
      posts_tree = archive_posts.chunk {|post| post.created_at.year}.map do |year, posts_of_year|
        [year, posts_of_year.chunk {|post| l(post.created_at, format: :plain_month_only) }]
      end

      result = []
      result << "<ul class=\"#{year_css}\">"
      posts_tree.each do |year, posts_by_month|
        result << "<li><a data-blogit-click-to-toggle-children>#{year}</a><ul class=\"#{month_css}\">"
        posts_by_month.each do |month, posts|
          result << "<li><a data-blogit-click-to-toggle-children>#{CGI.escape_html(month)}</a><ul class=\"#{post_css}\">"
          posts.each do |post|
            result << "<li>#{link_to(post.title, post)}</li>"
          end
          result << "</ul></li>"
        end
        result << "</ul></li>"
      end
      result << "</ul>"

      result.join.html_safe
    end

  end

end

app/views/blogit/posts/_active_record_comments.html.erb
<div id="comments">
  <%= render post.comments %>
</div>
<%= render partial: "blogit/comments/form", locals: { post: post, comment: comment } %>

app/views/blogit/posts/_blogger_information.html.erb
<%= blog_tag :footer do %>
    <%=t :written_by, scope: 'blogit.posts', author: post.blogger_display_name %>
    <%= time_tag(post.created_at, pubdate: true, format: blogit_conf.datetime_format) %>
<% end %>

app/views/blogit/posts/_comments_count.html.erb
<%= content_tag(:div, class: "blog_post_comments_count", id: "blog_post_#{post.id}_comments_count") do %>
  <%= link_to(post_path(post, anchor: "comments")) do %>
    <%=t :comment, scope: 'blogit.posts', count: post.comments_count %>
  <% end %>
<% end %>

app/views/blogit/posts/_disqus_comments.html.erb
 <div id="disqus_thread"></div>
 <script type="text/javascript">
   /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
   var disqus_shortname = '<%= Blogit.configuration.disqus_shortname %>'; // required: replace example with your forum shortname

   /* * * DON'T EDIT BELOW THIS LINE * * */
   (function() {
     var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
     dsq.src = '<%= request.protocol %>' + disqus_shortname + '.disqus.com/embed.js?<%= request.protocol_name %>';
     (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
   })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/blogit/posts/_empty.html.erb
<div class="blogit_empty_message">
  <%=t :there_are_no_posts_about, scope: 'blogit.posts', tag: params[:tag] %>
</div>

app/views/blogit/posts/_form.html.erb
<%= form_for(@post, html: {class: "new_blog_post", id: "new_blog_post"}) do |f| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%=t :prohibited_this_post_from_being_saved, scope: 'blogit.posts', count: @post.errors.count%></h2>

      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <%= field do %>
      <%= f.text_field :title, placeholder: t(:give_your_post_a_title, scope: 'blogit.posts') %>
    <% end %>

    <%= field do %>
      <%= f.text_area :body, placeholder: t(:write_something_here, scope: 'blogit.posts') %>
    <% end %>
  </fieldset>

  <fieldset>

    <%= field id: "new_blog_post_tag_field" do %>
      <%= f.label :tag_list, t(:tags, scope: 'blogit.posts') %>
      <%= f.text_field :tag_list, placeholder: t(:tag_placeholder, scope: 'blogit.posts') %>
    <% end %>

    <p class="blog_post_tip">
      <%=t :tip_you_can_style_your_post_using, scope: 'blogit.posts', parser: blogit_conf.default_parser %>
    </p>

  </fieldset>

  <%= actions do %>
    <%= f.submit %> <%=t :or, scope: 'blogit.posts'%>
    <%= link_to(t(:cancel, scope: 'blogit.posts'), @post.new_record? ? blog_root_path : post_path(@post)) %>
  <% end %>

<% end %>

app/views/blogit/posts/_pagination.html.erb
<%= paginate(@posts) %>

app/views/blogit/posts/_post_links.html.erb
<%= login_required do  %>
  <%= actions do %>
    <%= link_to(t(:edit, scope: 'blogit.posts'), edit_post_path(post)) %> | <%= link_to(t(:delete, scope: 'blogit.posts'), post, method: :delete, confirm: t(:are_you_sure_you_want_to_remove_this_post, scope: 'blogit.posts')) %>
  <% end %>
<% end unless blogit_conf.author_edits_only and not this_blogger?(post) %>

app/views/blogit/posts/_share_bar.html.erb
<div id="blog_share_bar">

  <div id="google-plus" class="social_button">
    <!-- GOOGLE +1 -->
    <g:plusone size="medium"></g:plusone>
    <script type="text/javascript">
      window.___gcfg = {lang: '<%= I18n.default_locale %>'};

      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- /GOOGLE +1 -->
  </div>

  <div id="twitter" class="social_button">
    <!-- TWITTER -->
    <a href="https://twitter.com/share" class="twitter-share-button"
        data-lang="<%= I18n.default_locale %>"
        data-url="http://<%= request.host_with_port %><%= request.path.gsub("//","/") %>"
        data-via="<%= Blogit.configuration.twitter_username %>"
        data-text="<%= post.title%>"
        data-count="horizontal">Tweet</a>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    <!-- /TWITTER -->
  </div>

  <div id="facebook" class="social_button">
    <!-- FACEBOOK LIKE -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/<%= t "blogit.share_bar.facebook" %>/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="fb-like" data-send="false"  data-layout="button_count" data-width="90" data-show-faces="false"></div>
    <!-- /FACEBOOK LIKE -->
  </div>

</div>

app/views/blogit/posts/edit.html.erb
<h2><%=t :edit_blog_post, scope: 'blogit.posts', id: @post.id %></h2>

<%= render 'form' %>

app/views/blogit/posts/new.html.erb
<h2><%=t :write_a_new_blog_post, scope: 'blogit.posts'%></h2>

<%= render 'form' %>

app/views/blogit/posts/show.html.erb
<%= render @post %>
<%= share_bar_for @post %>
<%= render "blogit/posts/post_footer", post: @post %>
<%= comments_for @post %>